### ISSUE TITLE
Update to WHATWG Specs

### ISSUE THREAD

**Issue by diegobfernandez** [arv/DOM-URL-Polyfill#2]
Since WHATWG Specs are earlier isn't it a good ideia to implement it?
Altough it might be good to help the spec.

Particulary I think the WHATWG spec is easier.

Anyway I'll fork your project and start working on updating the lib.

:)

**Comment by arv** [comment]
I think you are better off using https://github.com/Polymer/URL

**Comment by diegobfernandez** [comment]
That is also outdated. http://url.spec.whatwg.org
Do you think that is a better starting point?

**Comment by arv** [comment]
I'm pretty sure url.spec.whatwg.org is the latest one.

**Comment by techniq** [comment]
@arv - Might be a good idea to put a link to Polymer/URL in the README?
